my @revisions = (
    {
        name => "mkSyn_MemScanChain",
        toplevel => "mkSyn_MemScanChain"
    }
);

my $BLUESPECDIR=$ENV{BLUESPECDIR};
my $BLUELINKDIR=$ENV{BLUELINKDIR};
my $project="modulesyn";

# Generate qpf file

open OFH, ">$project.qpf";

printf OFH "# Generated by synModule.pl\n";
printf OFH "\n";

printf OFH "QUARTUS_REVISION=\"13.1\"\n";

foreach $rev (@revisions) {
    printf OFH "PROJECT_REVISION=\"$rev{name}\"\n"
}




for $rev (@revisions) {
    printf "name=$rev->{name}\n";
    printf "toplevel=$rev->{name}\n";

    open QSFH,  ">$rev->{name}.qsf";
    
    
    # Generate qsf file for each revision
    
    printf QSFH "set_global_assignment -name FAMILY \"Stratix V\"\n";
    printf QSFH "set_global_assignment -name DEVICE 5SGXEA7H2F35C2\n";
    printf QSFH "set_global_assignment -name ORIGINAL_QUARTUS_VERSION 13.1\n";
    printf QSFH "set_global_assignment -name PROJECT_CREATION_TIME_DATE \"12:50:05  DECEMBER 03, 2015\"\n";
    printf QSFH "set_global_assignment -name LAST_QUARTUS_VERSION 13.1\n";
    printf QSFH "set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0\n";
    printf QSFH "set_global_assignment -name MAX_CORE_JUNCTION_TEMP 85\n";
    printf QSFH "set_global_assignment -name POWER_PRESET_COOLING_SOLUTION \"23 MM HEAT SINK WITH 200 LFPM AIRFLOW\"\n";
    printf QSFH "set_global_assignment -name POWER_BOARD_THERMAL_MODEL \"NONE (CONSERVATIVE)\"\n";
    printf QSFH "set_global_assignment -name STRATIX_DEVICE_IO_STANDARD \"2.5 V\"\n";
    
    printf QSFH "set_global_assignment -name PARTITION_NETLIST_TYPE SOURCE -section_id Top\n";
    printf QSFH "set_global_assignment -name PARTITION_FITTER_PRESERVATION_LEVEL PLACEMENT_AND_ROUTING -section_id Top\n";
    printf QSFH "set_global_assignment -name PARTITION_COLOR 16764057 -section_id Top\n";
    
    
    # Bluespec conventions for toplevel interface
    printf QSFH "set_instance_assignment -name VIRTUAL_PIN ON -to *_get\n";
    printf QSFH "set_instance_assignment -name VIRTUAL_PIN ON -to *_put\n";
    printf QSFH "set_instance_assignment -name VIRTUAL_PIN OFF -to ha_pclock\n";
    printf QSFH "set_instance_assignment -name VIRTUAL_PIN ON -to ha_*\n";
    printf QSFH "set_instance_assignment -name VIRTUAL_PIN ON -to ah_*\n";
    
    printf QSFH "set_global_assignment -name VERILOG_SHOW_LMF_MAPPING_MESSAGES OFF\n";
    
    # BlueLink libs
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUELINKDIR/Altera/MLAB_0l.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUELINKDIR/Altera/BRAM2.Stall.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUELINKDIR/Altera/BRAM2.Fixed.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUELINKDIR/PSLVerilog/revwrap.v\n";
    
    # Bluespec libs
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/SizedFIFO.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/Counter.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFOL20.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFOL10.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFOL2.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFOL1.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFO20.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFO10.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFO2.v\n";
    printf QSFH "set_global_assignment -name VERILOG_FILE $BLUESPECDIR/Verilog/FIFO1.v\n";
    
    printf QSFH "set_instance_assignment -name PARTITION_HIERARCHY root_partition -to | -section_id Top\n";
    
    my $DUT_MODNAME="$rev->{name}";
    my $DUT_FN="$rev->{toplevel}.v";
    my $SDC_FN="sdc250m.sdc";
    
    # Toplevel
    printf QSFH "set_global_assignment -name VERILOG_FILE $DUT_FN\n";
    
    printf QSFH "set_global_assignment -name SDC_FILE $SDC_FN\n";
    
    printf QSFH "set_global_assignment -name TOP_LEVEL_ENTITY afu\n";
    
    printf QSFH "set_global_assignment -name VERILOG_MACRO \"DUTMODULETYPE=$DUT_MODNAME\"\n";
}
